version: '3.4'

services:
  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
        SA_PASSWORD: "Password1!"
        ACCEPT_EULA: "Y"
        MYSQL_DATABASE: StudentsEventsAuthDb
    ports:
        - 1433:1433

  studentsevents.api:
    image: ${DOCKER_REGISTRY-}studentseventsapi
    restart: always
    build:
      context: .
      dockerfile: StudentsEvents.API/Dockerfile
    ports:
      - 5000:443
    depends_on:
      - db
